---
- name: Configure SOE
  hosts: all
  remote_user: devops
  become: true
  vars:
    - system_owner: Clyse@exmaok.com
  tasks:
  - name: configure /etc/motd {{ inventory_hostname }}
    template:
      src: motd.j2
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644