---
- name: starting web service on web servers
  become: yes
  hosts: all
  tasks: 
  - name: starting web service
    service: 
      name: httpd
      state: started
      enabled: yes
    when: "'web' in inventory_hostname"
  - name: starting Postgresql service
    service: 
      name: postgresql
      state: started
      enabled: yes
    when: "'db' in inventory_hostname or 'admin' in inventory_hostname"
    