---
- name: Task failure Exercies
  hosts: all
  become: yes
  vars:
    web_pkg: http
    db_pkg: mariadb-server
    db_svc: mariadb
  tasks:
  - name: Web Server block
    block:
    - name: Install {{ web_pkg }}
      yum:
        name: "{{ web_pkg }}"
        state: present
    rescue:  
    - name: Install {{ db_pkg }}
      yum:
        name: "{{ db_pkg }}"
        state: present
    always:
    - name: start {{ db_svc }}
      service:
        name: "{{ db_svc }}"
        state: started