---
- name: Task failure Exercies
  hosts: all
  become: yes
  vars:
    web_pkg: httpd
    db_pkg: mariadb-server
    db_svc: mariadb
  tasks:
  - name: Check local time
    command: date
    register: command_result
    changed_when: false
  - debug:
      var: command_result.stdout
  - name: Web Server block
    block:
    - name: Install {{ web_pkg }}
      yum:
        name: "{{ web_pkg }}"
        state: present
      failed_when: web_package == "httpd"
    rescue:  
    - name: Install {{ db_pkg }}
      yum:
        name: "{{ db_pkg }}"
        state: present
    always:
    - name: start {{ db_svc }}
      service:
        name: "{{ db_svc }}"
        state: started