---
- name: Check Distro condition
  hosts: all
  become: yes
  vars:
    supported_distros:
      - RedHat
      - Fedora
  tasks:
  - name: INstall
    yum:
      name: httpd
      state: present
    #when: ansible_distribution in supported_distros
    when: >
      ( ansible_distribution == "RedHat" and
      ansible_distribution_major_version == "7" )
      or
      ( ansible_distribution == "Fedora" and
      ansible_distribution_major_version == "28" )
