---
- name: MariaDB Install
  hosts: database
  become: yes
  vars:
    db_packages:
    - mariadb-server
    - python3-PyMySQL
    db_service: mariadb
    resources_url: http://materials.example.com/labs/control-handlers
    config_file_url: "{{ resources_url }}/my.cnf.standard"
    config_file_dst: /etc/my.cnf
  tasks:
  - name: "{{ db_packages }} packags are installed"
    yum:
      name: "{{ db_packages }}"
      state: present
    notify:
      - set db password

  - name: Start the db service
    service:
      name: "{{ mariadb }}"
      state: started
      enabled: yes

  - name: Configure
    get_url:
      url: "{{ config_file_url }}"
      dest: "{{ config_file_dst }}"
      owner: mysql
      group: mysql
      force: yes
    notify:
      - restart db service

  handlers:
  - name: restart db service
    service:
      name: "{{ db_service }}"
      state: restarted

  - name: set db password
    mysql_user:
      name: root
      password: redhat