---
- name: Testing force handlers to start
  hosts: all
  become: yes
  force_handlers: yes
  tasks:
  - name: A Tasks which always notifies its handlers
    command: /bin/true
    notify: restart the database
  - name: A which fails
    yum:
      name: notpkg
      state: latest
  handlers: 
  - name: restart the database
    service:
      name: mariadb
      state: restarted