---
- name: Creating internal Software Repo
  hosts: database
  become: yes
  gather_fact: no
  tasks: 
  - name: Downloading GPG KEy
    rpm_key:
      key: http://repo.mysql.com/RPM-GPG-KEY-mysql.
      state: present
  - name: Creating MY SQL Repo on {{ inventory_hostname }}
    yum_repository:
      file: mysql80-community
      name: mysql80-community
      description: MySQL 8.0 YUM Repo
      baseurl: http://repo.mysql.com/yum/mysql-8.0-community/el/8/x86_64/
      gpgcheck: yes
      enabled: yes
