---
- name: Creating at job
  hosts: webservers
  become: yes
  tasks:
  - name: One minute Date in future
    at:
      command: date >> /home/devops/my_at_date_time
      unique: yes
      count: 1
      units: minutes
      state: present
