---
- name: Add text to an existing file
  hosts: all
  remote_user: root
  tasks:
  - name: Add a single line of text to a file
    lineinfile:
      line: This line was added by the lineinfile module.
      path: /home/devops/users.txt
      state: present